wordlist:
	edictor wordlist --data=../cldf/cldf-metadata.json --name=yotonahua --addon=cognacy:cog --preprocessing=align.py

sqlite:
	edictor wordlist --sqlite --data=../cldf/cldf-metadata.json --name=yotonahua --addon=cognacy:cog --preprocessing=align.py
