wordlist:
	edictor wordlist --data=../cldf/cldf-metadata.json --name=yotonahua --addon=cognacy:cog,conceptinsource:concept_in_source,concept_spanish_gloss:spanish --preprocessing=align.py

sqlite:
	edictor wordlist --sqlite --data=../cldf/cldf-metadata.json --name=yotonahua --addon=cognacy:cog,conceptinsource:concept_in_source,concept_spanish_gloss:spanish --preprocessing=align.py
